### ISSUE TITLE
首页根据角色不同变化

### ISSUE THREAD

**Issue by Ryan2018-js** [dbfu/fluxy-admin-web#4]
之前用vue项目，动态菜单，默认登录后进入动态菜单第一项，也可以说动态菜单的第一项，默认是首页，但这个路径还是动态菜单的正常路径，并非/。这样就不用提前在router中定义首页了。刚接触react项目，不知道这个需求是否可行？

**Comment by dbfu** [comment]
可以在页面初始化中判断当前路由是否为/，如果是/，就用router.navigate方法跳转到默认路由。

**Comment by Ryan2018-js** [comment]
感谢解答
