### ISSUE TITLE
本地前端跑不起来，无法连接代理地址。

### ISSUE THREAD

**Issue by hiddendeer** [dbfu/fluxy-admin-web#6]
[vite] ws proxy error:
Error: connect ECONNREFUSED 180.163.28.105:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)

加了secure: false 配置也不管用，请问这个怎么处理。

**Comment by dbfu** [comment]
https://www.fluxyadmin.cn 代理地址改成这个，加了个www
